### PR TITLE
Create zh_HK.lang

### PR DESCRIPTION
**Pull request by pakhei123**
thx for the one who translated chinese simplified

### CODE REVIEW

**Comment by xbony2** [comment]
Um... this should be two different files, not one combined file.

**Comment by pakhei123** [comment]
the tw chinese and hk chinese are both traditional chinese and they are similar(the difference is like the us and uk English) so maybe use this file for both or use is as zh_hk as i am from hong kong

**Comment by xbony2** [comment]
Just rename this file to zh_TW.lang, and make a new file called zh_HK.lang with the same contents.

**Comment by xbony2** [comment]
The name of the files, not the pull request :P

**Comment by xbony2** [comment]
I'll take care of it I guess, thanks for contribution.

**Pull request merged**
