### PR TITLE
Add dragon api and fix #188

### LINKED ISSUE #188: Include DragonAPI
@maggi373 RotaryCraft won't load without so I can't test from the dev environment, even if it compiles and stuff (not that I plan to test much but still). Also for the files in `libs`, there should be a corresponding LICENSE file (like [LICENSE-BigReactors](https://github.com/xbony2/Nuclear-Control/blob/master/LICENSE-BigReactors)) for compliance reasons. Thanks a lot for help with this stuff.

### PR DESCRIPTION
**Pull request by maggi373**
Add dragon api and fix #188
also added the missing license for rotarycraft

### CODE REVIEW

**Comment by maggi373** [comment]
the license is a bit troubling, my english skills are not up to task to deduct if we are breaking it or not. I've been looking for reikas maven but has been unable to do so. I dont think nc2 uses any code, just referencing.

**Comment by xbony2** [comment]
We might be, but I don't think Reika will care 🤷

**Comment by maggi373** [comment]
it is possible to make gradle download the files from curseforge tho, there are several ways to do it and there is a new way added for such events in gradle version that is being used now. cant find it anymore howerer, also nc2 are using the api so its only the question of redistrobution.

**Comment by xbony2** [comment]
Could be worth looking into I suppose, better to not be yelled at.

**Pull request merged**
