### PR TITLE
Update RecipesOld.java

### PR DESCRIPTION
**Pull request by Chocohead**
Updated for the new items and blocks added, as well as fixing other things that have broken.

Also restructured it, mainly so I could read it :P

It might need re-pulling if the Energy Sensor Kit is still missing a recipe, as I wasn't sure whether it was IC2Items.getItem("eumeter" or "eureader").

### CODE REVIEW

**Comment by xbony2** [comment]
I think it's "ecMeter" :P that's what I got from this(http://forum.industrial-craft.net/index.php?page=Thread&postID=174186#post174186) list.

**Comment by xbony2** [comment]
Btw, a lot of weird structuring was from Eclipse's refactor feature, which is different from my idea of refactor.

**Comment by Chocohead** [comment]
There we go, fixed

**Comment by xbony2** [comment]
Hopefully it works, but if it doesn't you can always send a second pull request :P

**Pull request merged**
