### PR TITLE
fix opengui permission override on cauldron servers

### PR DESCRIPTION
**Pull request by l89669**
fire event to test permission before open block gui to player.

### CODE REVIEW

**Comment by xbony2** [comment]
Have you tested that this works perfectly outside a cauldron environment?

**Comment by l89669** [comment]
it works well on a client, but it has nerver been tested on a forge server.

**Comment by l89669** [comment]
i mean, it works well on a client(both online and single mode)

**Comment by xbony2** [comment]
It's probably fine then.

**Comment by xbony2** [comment]
There's been a few fixes pushed back so I'll try to push this out and get it done with. New release soon (TM)

**Pull request merged**
