### PR TITLE
update cape module

### PR DESCRIPTION
**Pull request by maggi373**
an update for the cape module, i dont know if ya want to add this but its there, you will also get an fix for your json so capes will work again

### CODE REVIEW

**Comment by maggi373** [comment]
several other modpacks had to remove this module because of the outdated module and the json file is bad making other mods capes not work like mine. Turning off capes in the settings page wont fix this problem

**Comment by xbony2** [comment]
This mod is discontinued but if it's breaking a lot of things I can try to (merge this and) publish a new version.

**Comment by xbony2** [comment]
(see also https://github.com/xbony2/xbony2.github.io/pull/8 )

**Comment by maggi373** [comment]
It's not an importnant thing, there are several forked version fixing this. Just that its rather an easy fix and releasing it. I can think of smaller modpack devs not including this mod because of reasons they might have.

**Comment by maggi373** [comment]
You can also make another branch and release an cape fix version for those needing it and dont know how to compile themself

**Comment by maggi373** [comment]
Its also an security issue by using http and not https, you are open to man in the middle attacks

**Comment by xbony2** [comment]
Took a long time but im gonna do it

**Comment by xbony2** [comment]
It's gonna take a while to actually release this though since the build is totally broken by migrated resources and so on

**Pull request merged**
